project_name: kots
release:
  github:
    owner: replicatedhq
    name: kots
builds:
  - id: kots
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/kots/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/kots/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/kots/pkg/version.gitSHA={{.FullCommit}}
      -X github.com/replicatedhq/kots/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: kots
    hooks: {}
  - id: so
    goos:
    - linux
    goarch:
    - amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    main: ./ffi
    ldflags: -s -w
      -X github.com/replicatedhq/kots/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/kots/pkg/version.gitSHA={{.FullCommit}}
      -X github.com/replicatedhq/kots/pkg/version.buildTime={{.Date}}
    flags: -buildmode=c-shared
    binary: kots.so
    hooks: {}

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
